### ISSUE TITLE
RuntimeError: storage has wrong size: expected -8935141660703063632 got 110592

### ISSUE THREAD

**Issue by leondelee** [Sekunde/3D-SIS#2]
I ran the example.sh as guided but I got an error message:
RuntimeError: storage has wrong size: expected -8935141660703063632 got 110592
Any help will be appreciated :)
`]0;IPython: pointmatching/3D-SISCalled with args:
Namespace(cfg='ScanNet/example', debug=False, epochs=100000, gpu='0', mode='benchmark', num_workers=1, output_dir='example_result/scannet_benchmark_checkpoint', step='1205541', tag=None)
Using configs:
{'ALLOW_BORDER': 0,
 'ANCHORS_TYPE_LEVEL1': 'scannet14_3.txt',
 'ANCHORS_TYPE_LEVEL2': 'scannet14_11.txt',
 'ANCHORS_TYPE_LEVEL3': '',
 'BASE_IMAGE_PATH': 'example_result/scannet_benchmark_example_data/images',
 'BATCH_SIZE': 1,
 'BG_THRESH': 0.2,
 'BG_THRESH_LO': 0.0,
 'BIAS_DECAY': False,
 'CLASS_BATCH_SIZE': 16,
 'CLASS_POOLING_SIZE': 4,
 'CLASS_THRESH': 0.5,
 'COLOR_MEAN': [0.496342, 0.466664, 0.440796],
 'COLOR_STD': [0.277856, 0.28623, 0.291129],
 'DEBUG': False,
 'DEPTH_SHAPE': [41, 32],
 'DISPLAY': 10,
 'DOUBLE_BIAS': True,
 'FG_FRACTION': 0.5,
 'FG_THRESH': 0.5,
 'FILTER_ANCHOR_LEVEL1': '',
 'FILTER_ANCHOR_LEVEL2': '',
 'FILTER_ANCHOR_LEVEL3': '',
 'FIRST_TIME_ANCHORS': True,
 'FIX_BACKBONE': False,
 'FIX_CLASS': False,
 'FIX_ENET': True,
 'FIX_RPN': False,
 'FLIP_TSDF': False,
 'GAMMA': 0.1,
 'IMAGE_EXT': '.jpg',
 'IMAGE_SHAPE': [328, 256],
 'IMAGE_TYPE': 'color',
 'INIT_TRUNCATED': True,
 'INTRINSIC': [[37.01983, 0, 20, 0],
               [0, 38.5247, 15.5, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]],
 'KEEP_THRESH': 1.0,
 'LABEL_MAP': 'datagen/fileLists/nyu40labels_scannet.csv',
 'LEARNING_RATE': 5e-06,
 'LOAD_BACKBONE': True,
 'LOAD_CLASS': True,
 'LOAD_RPN': True,
 'LOG_TSDF': False,
 'MAP_THRESH': 0.5,
 'MASK_BACKBONE': 'MaskBackbone',
 'MASK_FG_THRESH': 0.5,
 'MASK_ONLY_IMAGES': False,
 'MASK_THRESH': 0.5,
 'MASK_USE_IMAGES': False,
 'MAX_IMAGE': 400,
 'MAX_VOLUME': 2000000,
 'MODE': '',
 'MOMENTUM': 0.9,
 'NET': 'ScanNet_Backbone',
 'NORMALIZE_WEIGHTS': [0.3280746813009404,
                       3.9644974086960434,
                       5.459494152836571,
                       2.241522691584157,
                       4.820655512680854,
                       3.565918577548873,
                       3.538498341919445,
                       4.636521236560596,
                       5.445050937449535,
                       5.079250281008131,
                       6.2030429647735845,
                       4.622662494840168,
                       5.956294301248057,
                       5.459141107819665,
                       6.724871661883906,
                       5.832442848923174,
                       5.064773947290611,
                       6.738988357113375,
                       3.375217918833916],
 'NUM_2D_CLASSES': 41,
 'NUM_ANCHORS_LEVEL1': 3,
 'NUM_ANCHORS_LEVEL2': 11,
 'NUM_ANCHORS_LEVEL3': 0,
 'NUM_CLASSES': 19,
 'NUM_IMAGES': 5,
 'NUM_IMAGE_CHANNELS': 128,
 'NYUV2_FINETUNE': False,
 'ONLY_IMAGES': False,
 'PRETRAINED_ENET_PATH': 'example_result/scannet_enet_checkpoint/scannetv2_enet.pth',
 'PROJ_DEPTH_MAX': 4.0,
 'PROJ_DEPTH_MIN': 0.1,
 'RANDOM_NUM_IMAGES': False,
 'ROI_THRESH': 0.9,
 'RPN_BATCHSIZE': 64,
 'RPN_CHANNELS': 256,
 'RPN_FG_FRACTION': 0.5,
 'RPN_NEGATIVE_OVERLAP': 0.15,
 'RPN_POSITIVE_OVERLAP': 0.35,
 'SNAPSHOT_KEPT': 0,
 'STEPSIZE': [],
 'TEST': {'RPN_NMS_THRESH': 0.1,
          'RPN_POST_NMS_TOP_N': 200,
          'RPN_PRE_NMS_TOP_N': 400},
 'TEST_FILELIST': 'experiments/filelists/ScanNet/v2/example_scene.txt',
 'TEST_SAVE_DIR': 'example_result/test',
 'TRAIN': {'RPN_NMS_THRESH': 0.5,
           'RPN_POST_NMS_TOP_N': 500,
           'RPN_PRE_NMS_TOP_N': 1000},
 'TRAINVAL_FILELIST': 'experiments/filelists/ScanNet/v2/trainval.txt',
 'TRAIN_FILELIST': 'experiments/filelists/ScanNet/v2/train.txt',
 'TRUNCATED': 3.0,
 'USE_BACKBONE': True,
 'USE_CLASS': True,
 'USE_GT': True,
 'USE_IMAGES': True,
 'USE_IMAGES_GT': False,
 'USE_MASK': True,
 'USE_RPN': True,
 'VAL_FILELIST': 'experiments/filelists/ScanNet/v2/val_chunk.txt',
 'VAL_NUM': 20,
 'VAL_SAVE_DIR': 'example_result/val',
 'VAL_TIME': 2.0,
 'VOXEL_SIZE': 0.046875,
 'WEIGHT_DECAY': 0.0005}
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    benchmark(args)
  File "/home/neil/leondelee/pointmatching/3D-SIS/lib/model/trainval.py", line 71, in benchmark
    net.load_state_dict(torch.load(saved_model))
  File "/home/neil/anaconda3/envs/3dsis/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/neil/anaconda3/envs/3dsis/lib/python3.6/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected -8935141660703063632 got 110592`

**Comment by Sekunde** [comment]
Hi, 
I can not reproduce the error on my machine. It seems something wrong in loading torch model.
Maybe more details: 
what is your GPU memory?
Are you using pytorch  0.4.1?

**Comment by leondelee** [comment]
Ok, thanks! I have fixed this out. 😊
Unfortunately, I have encountered another question when I try to do the inference on the  ScanNetV2 Test Data<https://github.com/Sekunde/3D-SIS#download-test-data>. It seems that the contents in the folder “scenes/” do not match those in the folder “images/”.:
[cid:image002.png@01D50CE5.60980FC0]
Here I can not find something with a prefix “scene0462_00” in the folder “images/”, is that the reason that why I have encountered this problem?
Thank you very much!
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Sekunde** [comment]
I can not see your image though... but i check the images folder from scannetv2 test data, it is there..
