### ISSUE TITLE
Inference result visualization

### ISSUE THREAD

**Issue by haohlin** [Sekunde/3D-SIS#24]
Hello there, thanks for your awesome work!

I'm not encountering any problems. Just wondering how to generate the visualization results shown in [https://github.com/Sekunde/3D-SIS/blob/master/images/teaser.jpg](url) and the YouTube video. 

Are you still using Meshlab? How can I add the bounding boxes and labels to the result files?

Thank you in advance.

**Comment by Sekunde** [comment]
labels are added via Powerpoint, and we use Mitsuba to render the image. 
checkout this https://github.com/Sekunde/mitsuba_rendering

**Comment by haohlin** [comment]
Thank you! That really helps :)
