### ISSUE TITLE
 bounding boxes visualization

### ISSUE THREAD

**Issue by Monikake** [Sekunde/3D-SIS#27]
Thank you for the wonderful job!!. I got the output by running example demo i can see only segmented objects, but How to visualize bounding boxes on segmented objects in the output .ply file ??. Could you please clarify whether we will get 3D bounding boxes or not.

**Comment by Sekunde** [comment]
Thanks for following our work.
You got the 3D bounding boxes after running example demo stored in .npy file, e.g. in example_result/test/scene0144_00/pred_box.npy
We also provide a script to visualize it in voxel grid space. You can run:
python tools/visualization.py --path example_result/test --mode result
this command will read the information stored in .npy file and generate pred_bbox.ply (3D bounding box visualization) and scene.ply (voxels visualization) under e.g. example_result/test/scene0144_00/

**Comment by Monikake** [comment]
Thank you for faster reply and it is helpful. I can able to see the bounding boxes alone, but is there a way to visualize bounding boxes along with the objects in the 3D space.

Below attached image is from your paper.So is it possible to visualize like this, BBox with objects in the space.
![3d-sis](https://user-images.githubusercontent.com/29518208/77226763-d3c40600-6ba0-11ea-9bf2-babb47eedbe2.PNG)

**Comment by Sekunde** [comment]
In order to get this image, you need to transfer the bbox from voxel grid space to world space by using the matrix stored in e.g. example_result/scannet_benchmark_example_data/images_square/scene0144_00/world2grid.txt
And mapping the generated point cloud (e.g.example_result/visualization/scene01440_00.ply) to vertices in the mesh from scannet dataset itself.

**Comment by Monikake** [comment]
Since i'm new to ML, could you please help me to do it? 
Thanks in advance!

**Comment by Monikake** [comment]
It would be helpful if you add that code to the repo.
Thanks in advance.

**Comment by Sekunde** [comment]
sorry, we don't have time now for publishing this code; we may have time for that in the middle of May. stay tunned.

**Comment by Monikake** [comment]
When can we expect the publish of this code?
Thanks in advance!

**Comment by Sekunde** [comment]
Hi, we just pass the neurIPS ddl and now is in cvpr session, we will publish the code next week
