### ISSUE TITLE
I want to use the data taken by my 3d-camera.

### ISSUE THREAD

**Issue by ncy906302** [Sekunde/3D-SIS#30]
thank you for the readMe update.
I have successfully run the code in ubuntu 16.04 and cuda8 !

if I want to use the data taken by my 3d-camera, to predict the results with your model.
how can I do?
I don't know file .scene and world2grid.txt means.
world2grid is camera parameters?
How to generate these files?

**Comment by Sekunde** [comment]
world2grid is used for projecting 2d features to 3d; namely from world coordinate (where the mesh exists) to voxelgrid coordinates;
https://github.com/Sekunde/3D-SIS/blob/master/lib/datasets/dataset.py#L50-L53
this our dataloader for reading the .scene file; it is binary file. First 3 number is UNIT64 telling the X,Y,Z dimensions of the scene and then to sdf values (float32)
