### ISSUE TITLE
Which library are you using for visualizing the ply file from visualization folder?

### ISSUE THREAD

**Issue by ghost** [Sekunde/3D-SIS#32]
Thank you for the code. I was able to execute example.sh file however when I try to use the ply file generated I get an error like 
`RPly: Error reading 'red' of 'vertex' number 0        ] 0%
Read PLY failed: unable to read file: example_result/visualization/scene0144_00.ply
PointCloud with 142719 points.`

I have tried 3 different libraries,Open3d, pyntcloud, and pytorch3D (separately) to visualize the ply file but I keep on getting the same error. 
I could visualize the ScanNetv2 ply data with all those 3 libraries BTW.

**Comment by Sekunde** [comment]
Hi, we use plyData to visualize, maybe you could run this commit 9fdf7ab2b433e2cbdbe118d81a3b7898eab792fc
to see if you can load the ply generated. I may introduce some bugs after this commit.
