### ISSUE TITLE
Inference on our own RGBD data

### ISSUE THREAD

**Issue by voyager1998** [Sekunde/3D-SIS#34]
Hi @Sekunde ,
Thanks for posting this, we were able to get the demo set up and running nicely, and the output was easy to interface with our ROS-based system. Like a couple of the other posters(#30, #8), we're struggling a bit to understand the workflow of getting from RGB-D camera data (ROS messages, pngs, whatever) into the `.scene` format in order to run it through the inference system. Could you post a baby-steps version of what you described in the "data generation" README? I think it would help people compare and cite this work more easily. Here is a list of things that we think might need clarification:
1. Generating `.scene` file from RGBD data, preferably from PNGs, but this is flexible. Ideally, this would be a sequence of command line instructions, including compilations if necessary.
2. How to modify the configuration file (`yaml` file) after generating the `.scene` file.

(We could use our existing OctoMap setup to do the voxelization, but it seems like your code already handles the RGBD->`.scene` process, so we thought we could reuse that.)

**Comment by Sekunde** [comment]
We use mLib to generate TSDF and pack it into binary file (.scene) in the following order
https://github.com/Sekunde/3D-SIS/blob/master/experiments/cfgs/ScanNet/example.yml#L88

you can generate TSDF by other code as well, e.g. https://github.com/tum-vision/fastfusion and https://github.com/andyzeng/tsdf-fusion-python. If you pack it into binary file as described, our dataloader should be able read it out.

You can modify this parameter in yaml:
 https://github.com/Sekunde/3D-SIS/blob/master/experiments/cfgs/ScanNet/example.yml#L32
which point to a .txt file like this
https://github.com/Sekunde/3D-SIS/blob/master/experiments/filelists/ScanNet/v2/example_scene.txt
where you can store the paths to the .scene or your binary file

**Comment by initrandom** [comment]
@voyager1998 Hi , were you able to generate the .scene file as you stated in 1.?

**Comment by kunzaiyy** [comment]
> We use mLib to generate TSDF and pack it into binary file (.scene) in the following order
> https://github.com/Sekunde/3D-SIS/blob/master/experiments/cfgs/ScanNet/example.yml#L88
> 
> you can generate TSDF by other code as well, e.g. https://github.com/tum-vision/fastfusion and https://github.com/andyzeng/tsdf-fusion-python. If you pack it into binary file as described, our dataloader should be able read it out.
> 
> You can modify this parameter in yaml:
> https://github.com/Sekunde/3D-SIS/blob/master/experiments/cfgs/ScanNet/example.yml#L32
> which point to a .txt file like this
> https://github.com/Sekunde/3D-SIS/blob/master/experiments/filelists/ScanNet/v2/example_scene.txt
> where you can store the paths to the .scene or your binary file

Excuse me，i can not find which mLib did you mean,there are a lot of mlib in github,so can you tell me the extract name of mlib? By the way ,i want to generate TSDF(.scene) from pcd or ply file,is there any better way to achieve it?Thank you very much.

**Comment by Sekunde** [comment]
https://github.com/niessner/mLib
this is the mlib link we use.

We assume an RGBD dataset, which contains the depth frames and its camera poses for generating TSDF. With ply file, it only has a reconstructed scene but no camera poses provided. Without camera poses, we can not really generate sdf, as a positive sign in our paper denotes the visible free space, which actually needs the camera poses; or you can redefine the positive sign as outside of the mesh in a watertight mesh (with this code https://github.com/christopherbatty/SDFGen). alternatively, you can generate an occupancy voxel grid or DF from a mesh.
