### ISSUE TITLE
How to test on own ply file?

### ISSUE THREAD

**Issue by initrandom** [Sekunde/3D-SIS#38]
Hi, I have read through the data generation instruction you have provided but still I am confused.

So, I have few indoor 3d data in ply format and I want to 3D-SIS on it? I have tried to go through data generation instruction but still, I am confused.

**I only have 3d data in ply format, what would be the baby step?**

**Comment by Sekunde** [comment]
You need to voxelize the pointcloud into sdf and store as the same binary format as showed in our dataloader. Maybe you can voxelize the pointcloud into binary voxel grid which is easier, but it could lead to worse performance.
