### ISSUE TITLE
scannetv2_test_data has a mismatch between scenes/ and images/

### ISSUE THREAD

**Issue by leondelee** [Sekunde/3D-SIS#4]
Hi,
I have recently encountered an issue when I tried to inference on scannetv2_test_data that you provided. However, I have configured everything as you guided, but got an error like this:
` [Errno 2] No such file or directory: '/home/neil/leondelee/pointmatching/3D-SIS/data/ScanNet/scannetv2_test_data/images/scene0462_00/depth'
`
It seems that there is a file called "scene0462_00_0_.scene" in the folder "scannetv2_test_data/scenes" but there isn't a folder like "scene0462_00/" in the folder "scannetv2_test_data/images/".
Any help will be appreciated!

**Comment by Sekunde** [comment]
Is this the only one missing, or there are also other scenes' images missing? Can you try to delete 'scene0462_00' from the experiments/filelists/ScanNet/v1/test.txt, and try to see if the error stills happens? Can you also paste the configuration file you are using for inference?

**Comment by leondelee** [comment]
Thanks!
My configuration file is: 
`
TRAIN: 
  RPN_NMS_THRESH: 0.5
  RPN_PRE_NMS_TOP_N: 1000 
  RPN_POST_NMS_TOP_N: 500 

TEST:
  RPN_PRE_NMS_TOP_N: 400
  RPN_POST_NMS_TOP_N: 200
  RPN_NMS_THRESH: 0.1

RPN_BATCHSIZE: 64
RPN_FG_FRACTION: 0.5
RPN_POSITIVE_OVERLAP: 0.35
RPN_NEGATIVE_OVERLAP: 0.15

CLASS_BATCH_SIZE: 16
FG_FRACTION: 0.5
FG_THRESH: 0.5
BG_THRESH: 0.2
BG_THRESH_LO: 0.0
USE_GT: True

VAL_TIME: 0.0
LEARNING_RATE: 0.001
TRAIN_FILELIST: experiments/filelists/ScanNet/v2/train.txt
VAL_FILELIST: experiments/filelists/ScanNet/v2/val_chunk.txt
TRAINVAL_FILELIST: experiments/filelists/ScanNet/v2/trainval.txt
TEST_FILELIST: experiments/filelists/ScanNet/v2/test.txt

SNAPSHOT_KEPT: 0
STEPSIZE: [500000, 600000]
WEIGHT_DECAY: 0.0005

ALLOW_BORDER: 0
VAL_SAVE_DIR: ../results/ScanNet/rpn_class_mask_5/val/
TEST_SAVE_DIR: ../results/ScanNet/rpn_class_mask_5/test/

ROI_THRESH: 0.9
CLASS_THRESH: 0.5
MAP_THRESH: 0.5

KEEP_THRESH: 1.0
LABEL_MAP: datagen/fileLists/nyu40labels_scannet.csv
TRUNCATED: 3.0

NUM_ANCHORS_LEVEL1: 3
NUM_ANCHORS_LEVEL2: 11
NUM_ANCHORS_LEVEL3: 0
ANCHORS_TYPE_LEVEL1: 'scannet14_3.txt'
ANCHORS_TYPE_LEVEL2: 'scannet14_11.txt'
ANCHORS_TYPE_LEVEL3: ''
FILTER_ANCHOR_LEVEL1: ''
FILTER_ANCHOR_LEVEL2: ''
FILTER_ANCHOR_LEVEL3: ''

BATCH_SIZE: 1
RPN_CHANNELS: 256
CLASS_POOLING_SIZE: 4
NET: ScanNet_Backbone
MASK_BACKBONE: MaskBackbone
VOXEL_SIZE: 0.046875

# back bone
LOAD_BACKBONE: True
USE_BACKBONE: True
FIX_BACKBONE: True

#RPN
LOAD_RPN: True
USE_RPN: True
FIX_RPN: True

#Classification
LOAD_CLASS: True
USE_CLASS: True
FIX_CLASS: True

# mask
USE_MASK: True

#-----------------------
# enet
# ----------------------
USE_IMAGES: True
ONLY_IMAGES: False
USE_IMAGES_GT: False

NUM_IMAGES: 5
BASE_IMAGE_PATH: '/home/neil/leondelee/pointmatching/3D-SIS/data/ScanNet/scannetv2_test_data/images'

IMAGE_TYPE: 'color'
IMAGE_EXT: '.jpg'
NUM_IMAGE_CHANNELS: 128
IMAGE_SHAPE: [328, 256]
DEPTH_SHAPE: [41, 32]

COLOR_MEAN: [0.496342, 0.466664, 0.440796]
COLOR_STD:  [0.277856, 0.28623, 0.291129]
INTRINSIC : [[37.01983, 0, 20, 0],
             [0, 38.52470, 15.5, 0],
             [0, 0, 1, 0],
             [0, 0, 0, 1]]


PRETRAINED_ENET_PATH: /home/neil/leondelee/pointmatching/3D-SIS/checkpoints/ScanNet/scannet_enet_checkpoint/scannetv2_enet.pth
FIX_ENET: True

`

I have changed the TEST_FILELIST from experiments/filelists/ScanNet/v1/test.txt to experiments/filelists/ScanNet/v2/test.txt and pointed the file experiments/filelists/ScanNet/v2/test.txt accordingly, hope that does not matter.

And when I deleted the line 'scene0462_00' another weird problem accurs: 
`Namespace(cfg='ScanNet/rpn_class_mask_5', debug=False, epochs=100000, gpu='0', mode='test', num_workers=1, output_dir='../checkpoints/', step='1205541', tag=None)
Using configs:
{'ALLOW_BORDER': 0,
 'ANCHORS_TYPE_LEVEL1': 'scannet14_3.txt',
 'ANCHORS_TYPE_LEVEL2': 'scannet14_11.txt',
 'ANCHORS_TYPE_LEVEL3': '',
 'BASE_IMAGE_PATH': '/home/neil/leondelee/pointmatching/3D-SIS/data/ScanNet/scannetv2_test_data/images',
 'BATCH_SIZE': 1,
 'BG_THRESH': 0.2,
 'BG_THRESH_LO': 0.0,
 'BIAS_DECAY': False,
 'CLASS_BATCH_SIZE': 16,
 'CLASS_POOLING_SIZE': 4,
 'CLASS_THRESH': 0.5,
 'COLOR_MEAN': [0.496342, 0.466664, 0.440796],
 'COLOR_STD': [0.277856, 0.28623, 0.291129],
 'DEBUG': False,
 'DEPTH_SHAPE': [41, 32],
 'DISPLAY': 10,
 'DOUBLE_BIAS': True,
 'FG_FRACTION': 0.5,
 'FG_THRESH': 0.5,
 'FILTER_ANCHOR_LEVEL1': '',
 'FILTER_ANCHOR_LEVEL2': '',
 'FILTER_ANCHOR_LEVEL3': '',
 'FIRST_TIME_ANCHORS': True,
 'FIX_BACKBONE': True,
 'FIX_CLASS': True,
 'FIX_ENET': True,
 'FIX_RPN': True,
 'FLIP_TSDF': False,
 'GAMMA': 0.1,
 'IMAGE_EXT': '.jpg',
 'IMAGE_SHAPE': [328, 256],
 'IMAGE_TYPE': 'color',
 'INIT_TRUNCATED': True,
 'INTRINSIC': [[37.01983, 0, 20, 0],
               [0, 38.5247, 15.5, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]],
 'KEEP_THRESH': 1.0,
 'LABEL_MAP': 'datagen/fileLists/nyu40labels_scannet.csv',
 'LEARNING_RATE': 0.001,
 'LOAD_BACKBONE': True,
 'LOAD_CLASS': True,
 'LOAD_RPN': True,
 'LOG_TSDF': False,
 'MAP_THRESH': 0.5,
 'MASK_BACKBONE': 'MaskBackbone',
 'MASK_FG_THRESH': 0.5,
 'MASK_ONLY_IMAGES': False,
 'MASK_THRESH': 0.5,
 'MASK_USE_IMAGES': False,
 'MAX_IMAGE': 400,
 'MAX_VOLUME': 2000000,
 'MODE': '',
 'MOMENTUM': 0.9,
 'NET': 'ScanNet_Backbone',
 'NORMALIZE_WEIGHTS': [0.3280746813009404,
                       3.9644974086960434,
                       5.459494152836571,
                       2.241522691584157,
                       4.820655512680854,
                       3.565918577548873,
                       3.538498341919445,
                       4.636521236560596,
                       5.445050937449535,
                       5.079250281008131,
                       6.2030429647735845,
                       4.622662494840168,
                       5.956294301248057,
                       5.459141107819665,
                       6.724871661883906,
                       5.832442848923174,
                       5.064773947290611,
                       6.738988357113375,
                       3.375217918833916],
 'NUM_2D_CLASSES': 41,
 'NUM_ANCHORS_LEVEL1': 3,
 'NUM_ANCHORS_LEVEL2': 11,
 'NUM_ANCHORS_LEVEL3': 0,
 'NUM_CLASSES': 19,
 'NUM_IMAGES': 5,
 'NUM_IMAGE_CHANNELS': 128,
 'NYUV2_FINETUNE': False,
 'ONLY_IMAGES': False,
 'PRETRAINED_ENET_PATH': '/home/neil/leondelee/pointmatching/3D-SIS/checkpoints/ScanNet/scannet_enet_checkpoint/scannetv2_enet.pth',
 'PROJ_DEPTH_MAX': 4.0,
 'PROJ_DEPTH_MIN': 0.1,
 'RANDOM_NUM_IMAGES': False,
 'ROI_THRESH': 0.9,
 'RPN_BATCHSIZE': 64,
 'RPN_CHANNELS': 256,
 'RPN_FG_FRACTION': 0.5,
 'RPN_NEGATIVE_OVERLAP': 0.15,
 'RPN_POSITIVE_OVERLAP': 0.35,
 'SNAPSHOT_KEPT': 0,
 'STEPSIZE': [500000, 600000],
 'TEST': {'RPN_NMS_THRESH': 0.1,
          'RPN_POST_NMS_TOP_N': 200,
          'RPN_PRE_NMS_TOP_N': 400},
 'TEST_FILELIST': 'experiments/filelists/ScanNet/v2/test.txt',
 'TEST_SAVE_DIR': '../results/ScanNet/rpn_class_mask_5/test/',
 'TRAIN': {'RPN_NMS_THRESH': 0.5,
           'RPN_POST_NMS_TOP_N': 500,
           'RPN_PRE_NMS_TOP_N': 1000},
 'TRAINVAL_FILELIST': 'experiments/filelists/ScanNet/v2/trainval.txt',
 'TRAIN_FILELIST': 'experiments/filelists/ScanNet/v2/train.txt',
 'TRUNCATED': 3.0,
 'USE_BACKBONE': True,
 'USE_CLASS': True,
 'USE_GT': True,
 'USE_IMAGES': True,
 'USE_IMAGES_GT': False,
 'USE_MASK': True,
 'USE_RPN': True,
 'VAL_FILELIST': 'experiments/filelists/ScanNet/v2/val_chunk.txt',
 'VAL_NUM': 20,
 'VAL_SAVE_DIR': '../results/ScanNet/rpn_class_mask_5/val/',
 'VAL_TIME': 0.0,
 'VOXEL_SIZE': 0.046875,
 'WEIGHT_DECAY': 0.0005}
loaded mode from ../checkpoints/ScanNet/rpn_class_mask_5/checkpoints/step_1205541.pth
starting test on whole scan....
  0%|                                                   | 0/311 [00:00<?, ?it/s]/home/neil/leondelee/pointmatching/3D-SIS/code/lib/datasets/dataset.py:68: RuntimeWarning: invalid value encountered in greater
  data = np.concatenate([trunc_abs_data, np.greater(data, -1)], 0)
/home/neil/leondelee/pointmatching/3D-SIS/code/lib/nets/network.py:546: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob_level1 = F.softmax(rpn_cls_score_level1)
/home/neil/leondelee/pointmatching/3D-SIS/code/lib/nets/network.py:559: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob_level2 = F.softmax(rpn_cls_score_level2)
/home/neil/leondelee/pointmatching/3D-SIS/code/lib/nets/network.py:597: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  cls_prob = F.softmax(cls_score)
/home/neil/anaconda3/envs/3dsis/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
  1%|▎                                          | 2/311 [00:11<35:41,  6.93s/it]Traceback (most recent call last):
  File "/home/neil/leondelee/pointmatching/3D-SIS/code/main.py", line 82, in <module>
    test(args)
  File "/home/neil/leondelee/pointmatching/3D-SIS/code/lib/model/trainval.py", line 94, in test
    SolverWrapper.test(net, dataloader, logger)
  File "/home/neil/leondelee/pointmatching/3D-SIS/code/lib/model/trainval.py", line 788, in test
    for iter, blobs in enumerate(tqdm(data_loader)):
  File "/home/neil/anaconda3/envs/3dsis/lib/python3.6/site-packages/tqdm/_tqdm.py", line 999, in __iter__
    for obj in iterable:
  File "/home/neil/anaconda3/envs/3dsis/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/neil/anaconda3/envs/3dsis/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/neil/anaconda3/envs/3dsis/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/neil/anaconda3/envs/3dsis/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/neil/leondelee/pointmatching/3D-SIS/code/lib/datasets/dataset.py", line 86, in __getitem__\n    labelid = self.mapping[labelid]\nKeyError: 1065353216\n'
`

**Comment by Sekunde** [comment]
![image](https://user-images.githubusercontent.com/6199161/58973332-fcb90d00-87bf-11e9-806b-59b13a9502c3.png)

I screenshot what i got from scannetv2_test_data. and i didn't get this "RuntimeWarning: invalid value encountered in greater data = np.concatenate([trunc_abs_data, np.greater(data, -1)], 0)".

it seems the data is corrupted. Can you add print(dimZ) after https://github.com/Sekunde/3D-SIS/blob/master/lib/datasets/dataset.py#L51 

Maybe also can you paste the .scene size like this
-rw-r--r-- 1 ji ji  2886940 Apr 26 15:23 scene0689_00__0__.scene
-rw-r--r-- 1 ji ji  5110448 Apr 26 15:23 scene0690_00__0__.scene

**Comment by Sekunde** [comment]
@leondelee i figure out the mismatch may be because the image folder names mismatch, maybe something helpful 
https://github.com/Sekunde/3D-SIS/issues/7#issuecomment-512229214
