### ISSUE TITLE
Big problems in the demo shell

### ISSUE THREAD

**Issue by hyuDev** [Sekunde/3D-SIS#40]
hello, I'm studying your thesis with the your code.
Thank you so much for sharing the code so that I can understand your thesis.
But  I need a more detailed explanation, because There are many difficulties in running the demo shell.
I followed the instructions, but I couldn't get any results.(ply files that visualizations will be stored in TEST_SAVE_DIR )

1. Should I do this part of [inference-on-scannetv2 ](https://github.com/Sekunde/3D-SIS#inference-on-scannetv2) before I turn on the demo?
2. The downloaded [scannetv2_test_datazip](http://kaldir.vc.in.tum.de/3dsis/scannetv2_test_data.zip) does not have an images folder. What exactly should BASE_IMAGE_PATH be? And I'm curious about the structure of BASE_IMAGE_PATH.
3.I make dir as [folder-structure](https://github.com/Sekunde/3D-SIS#folder-structure) created folders and unzipped file according to this structure. The paths used in cfg for the demo shell were placed in absolute paths along the structure, but they didn't work properly.

If you don't mind, Could you explain in more detail so I can run the demo?

best regards,

**Comment by Sekunde** [comment]
Hi,
the demo should automatically work w/o any other hassles. It should download scannet_benchmark_example_data. maybe you can paste error logs to see what happened?

if you unzip scannetv2_test_data.zip, it should have a images_square folder structured by scene ids, e.g. scannetv2_test_data/images_square/scene0011_00

**Comment by hyuDev** [comment]
hi, error msg is this.

 'WEIGHT_DECAY': 0.0005}
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    benchmark(args)
  File "/home/userml1/Desktop/3D-SIS-master/lib/model/trainval.py", line 64, in benchmark
    logger = Logger(os.path.join(log_dir, 'test'))
  File "/home/userml1/Desktop/3D-SIS-master/lib/utils/logger.py", line 15, in __init__
    self.writer = tf.summary.FileWriter(log_dir)
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Voxel to Mesh
generate visualization
evaluate mAP
ERROR: No result files found.

I have not Gpu device so I install torch 0.4.0 cpuonly version, 
you recommended the demo shell can running in cpu...
I run this ububtu 18.04, anaconda.
what can i do?

**Comment by Sekunde** [comment]
File "/home/userml1/Desktop/3D-SIS-master/lib/utils/logger.py", line 15, in init
self.writer = tf.summary.FileWriter(log_dir)
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

it seems something wrong in your tensorboard, you can find the correct tensorboard version that has FileWriter
