### ISSUE TITLE
size of image feature 

### ISSUE THREAD

**Issue by hfutdzx** [Sekunde/3D-SIS#45]
Hello，thank yor for sharing your codes.I have a question.
Why use the feature vector of 41x32 size instead of maintaining the original size?

**Comment by Sekunde** [comment]
We use an ENet as the 2D backbone and we project 2D features into 3D rather than RGB values, and ENet will reduce the image size to generate a 2D feature map.

**Comment by hfutdzx** [comment]
Thank you for your help！
