### ISSUE TITLE
semantic class label for chunk？

### ISSUE THREAD

**Issue by hfutdzx** [Sekunde/3D-SIS#47]
This is a wonderful work. Thank you for your contribution. This work is very helpful to me. I have a problem. I'm doing research on semantic category segmentation. I want to know how to use “datagen” code to mark semantic categories for voxels of each chunk？（20 class）

**Comment by Sekunde** [comment]
Hi, 

Thanks for following our work. "datagen" is used for generating instance-level annotations per chunk; not per-voxel annotations. You can download the per-voxel annotation (20 class) processed from [3dmv](https://github.com/angeladai/3DMV).

**Comment by hfutdzx** [comment]
Thanks a lot for your help！

**Comment by hfutdzx** [comment]
Hi，Prof.Hou，I have a question about the 3DMV train dataset.I used the 3DMV dataset to train 3DMV model，but I found that there were too many invalid samples in this dataset.more specifically，many 3D chunks have no mapping relationship with 2d images，and 3Dmv cannot be trained.
