### ISSUE TITLE
train the model on scannetv2

### ISSUE THREAD

**Issue by lapetite123** [Sekunde/3D-SIS#5]
thanks for your great work!
I want to train the model on scannetv2, but I don't see any command in readme.md used for training. what should I do for  training?

**Comment by Sekunde** [comment]
check this out: https://github.com/Sekunde/3D-SIS#train-your-own-model

**Comment by lapetite123** [comment]
hello，I tried to run the demo code, but it reported as follows:
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411

I also tried to run 'Inference on ScanNetV2', the same error as above, I don't know what the problem is. can you please help me.

**Comment by Sekunde** [comment]
@lapetite123 it seems some error about aten, which is introduced after pytorch 1.0.0. Can you check if yo u are using pytorch0.4.1?

**Comment by lapetite123** [comment]
pytorch version is 0.4.1, and the cuda version is 9.0

**Comment by Sekunde** [comment]
@lapetite123 I can run the code smoothly with GTX 1080Ti and CUDA 8.0. 

It seems there is compatible problem of PyTorch version 0.4.1 and new architecture card. 
(if you only have GTX 2080Ti, you may need to compile PyTorch 0.4.1 from source with CUDA10)

However, I hope this information could help: 
https://github.com/pytorch/pytorch/issues/7548#issuecomment-444349421
https://github.com/1adrianb/face-alignment/issues/123#issuecomment-452021425
