### ISSUE TITLE
Problem loading data when doing demo

### ISSUE THREAD

**Issue by yinlingluo** [Sekunde/3D-SIS#6]
I was trying to run the demo, and called 
"python main.py --cfg ScanNet/example --step 1205541 --output_dir example_result/scannet_benchmark_checkpoint --mode benchmark --gpu 0" in the shell.
(after set up those 3 src as required in example.sh)

Then I got: 
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    benchmark(args)
  File "/home/user/Team/YLLuo/3D-SIS-master/lib/model/trainval.py", line 73, in benchmark
    SolverWrapper.benchmark(net, dataloader, logger)
  File "/home/user/Team/YLLuo/3D-SIS-master/lib/model/trainval.py", line 682, in benchmark
    proj_mapping0, proj_mapping1 = zip(*real_proj_mapping)
ValueError: not enough values to unpack (expected 2, got 0)

I traceback the variables(trainval.py/benchmark()), found:
<real_proj_mapping>==[]
which is loaded from:
<proj_mapping> == [None, None, None,........] (all None's in it)
which is loaded from: < blobs> , and it seems fine...

Any idea help with this?
Thanks!

**Comment by Sekunde** [comment]
@yinlingluo hey, the **proj_mapping** is computed from depth and poses, if it is None, meaning this frame does not have a valid projection. From your description, it seems no frames have valid projection.
Can you check out blobs['nearest_images']['depths'][0]  and blobs['nearest_images']['pose'][0] values? it could be something missing in the depth or poses. Btw, did you run on CPU or GPU?

**Comment by yinlingluo** [comment]
@Sekunde Thanks for the quick response!
I checked those 3 values in blobs, the other two were fine, but blobs['nearest_image']['depths'][0] has almost all 0's in it. But when I try to check the max among those values in console, numpy gave me 0.001.
ps. I run it on GPU.

**Comment by Sekunde** [comment]
![image](https://user-images.githubusercontent.com/6199161/61115922-d6a81c00-a493-11e9-8a08-4867b756871b.png)
That is the screenshot from my end. I think there is something wrong in loading depth.
Can you checkout the values of depth_image in https://github.com/Sekunde/3D-SIS/blob/master/lib/datasets/dataset.py#L248-L253 ?

**Comment by yinlingluo** [comment]
The problem may be caused by the imread? I then use cv2.imread, and it works fine!
Thank you!
