### ISSUE TITLE
Demo code not working

### ISSUE THREAD

**Issue by mslivins** [Sekunde/3D-SIS#9]
Greetings!

Your `example.sh` doesn't seem to be working. Some issues I've found:

- Line 25: you call `example_result/test` but it does not exist
- Line 25: you call `example_result/benchmark_result` but it does not exist
- Line 33: ERROR: No result files found.

**Comment by Sekunde** [comment]
thanks for your feedback, we have fixed error, you can try it again (also re-download the data).
